billing_profiles/urls.py
from django.urls import path
from . import views

app_name='billing_profiles'

urlpatterns = [
    path('nuevi', views.create,name='create')
]

carts/urls.py
from django.urls import path
from . import views
app_name= 'carts'

urlpatterns = [
    path('',views.cart, name='cart'),
    path('agregar',views.add, name='add'),
    path('eliminar',views.remove, name="remove"),
]

facilito_store/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from . import views
from products.views import ProductListView
from django.conf.urls.static import static
from django.conf import settings




urlpatterns = [
    path('',ProductListView.as_view(), name='index'),
    path('usuarios/login', views.login_view, name='login'),
    path('usuarios/logout', views.logout_view, name='logout'),
    path('usuarios/register', views.register, name='register'),
    path('admin/', admin.site.urls),
    path('productos/',include('products.urls')),
    path('carrito/',include('carts.urls')),
    path('orden/',include('orders.urls')),
    path('direcciones/',include('shipping_addresses.urls')),
    path('codigos/', include('promo_codes.urls')),
    path('pagos/', include('billing_profiles.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('',views.order, name='order'),
    path('direccion', views.address, name='address'),
    path('seleccionar/direccion',views.select_address, name='select_address'),
    path('establecer/direccion/<int:pk>', views.check_address, name='check_address'),
    path('confirmacion',views.confirm, name='confirm'),
    path('cancelar', views.cancel,name='cancel'),
    path('completar', views.complete,name='complete'),
    path('completados', views.OrderListView.as_view(),name='completeds'),
]

shipping_addresses/urls.py
from django.urls import path
from .import views

app_name = 'shipping_addresses'

urlpatterns = [
    path('',views.ShippingAddressListView.as_view(), name='shipping_addresses'),
    path('nuevo',views.create,name='create'),
    path('editar/<int:pk>', views.ShippingAddressUpdateView.as_view(), name='update'),
    path('eliminar/int:<int:pk>',views.ShippingAddressDeleteView.as_view(),name='delete'),
    path('default/<int:pk>', views.default,name='default')
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Document</title>

    {% block css %}
    {% endblock %}
</head>

<body>
    {% include 'navbar.html' %}
    <div class="container">
        {% include 'messages.html' %}

        {% block breadcrumb %}

        {% endblock %}
        <div class="row mt-3">
            {% block content %}
            {% endblock %}
        </div>
    </div>
    {% comment %} font awesome kit {% endcomment %}
    <script src="https://kit.fontawesome.com/c2286c5998.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
    {% block javascript %}
    {% endblock %}
</body>

</html>

templates/index.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <h4 class="text-center">{{message}}</h4>
            {% include "products/snippets/search.html" %}
            {% include 'products/snippets/list.html' %}
            {% if is_paginated %}
            <ul class="pagination mt-4">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a href="?page={{page_obj.previous_page_number}}" class="page-link">Previous</a>
                </li>
                {% endif %}
                
                {% for i in paginator.page_range %}
               
                {% if page_obj == i %}
                <li class="page-item">
                    <a href="?page={{i}}" class="page-link active">{{i}}</a>
                </li>
                {% else %}
                <li class="page-item">
                    <a href="?page={{i}}" class="page-link">{{i}}</a>
                </li>
                {% endif %}

                {% endfor %}

                {% if page_obj.has_next %}
                <li class="page-item">
                    <a href="?page={{page_obj.next_page_number}}" class="page-link">Next</a>
                </li>
                {% endif %}
            </ul>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

templates/messages.html
{% if messages %}
{% for message in messages %}
<div class="alert {% if message.tags == 'success'%}alert-success{% else %}alert-danger{% endif %}">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    {{message}}
</div>
{% endfor %}
{% endif %}

templates/navbar.html
{% url 'index' as index %}
{% url 'login' as login %}
{% url 'register' as register %}
{% url 'carts:cart' as cart %}
{% url 'shipping_addresses:shipping_addresses' as shipping_addresses %}
{% url 'orders:completeds' as completeds %}
{% url 'billing_profiles:create' as billing_profiles %}


<nav class="navbar fix-top navbar-expand-md bg-dark navbar-dark">
    <div class="container-fluid">
        <a href="{{index}}" class="navbar-brand">Facilito Store</a>
        <button type="button" class="navbar-toggler navbar-toggler-right" data-bs-toggle="collapse"
            data-bs-target="#navba">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div id="navba" class="collapse navbar-collapse hide">
            <ul class="navbar-nav">
                <li class="navbar-item">
                    <a href="{{cart}}" class="nav-link {% if request.path == cart %}active{% endif %}">
                        Mi carro <span class="fa fa-shopping-cart"></span>
                    </a>
                </li>
                {% if user.is_authenticated %}
                <li class="navbar-item">
                    <a href="{{shipping_addresses}}"
                        class="nav-link {% if request.path == shipping_addresses %}active{% endif %}">
                        Mis direcciones <span class="fa fa-location-dot"></span>
                    </a>
                </li>
                <li class="navbar-item">
                    <a href="{{completeds}}" class="nav-link {% if request.path == completeds %}active{% endif %}">
                        Mis Pedidos <span class="fa fa-shipping-fast"></span>
                    </a>
                </li>
                <li class="navbar-item">
                    <a href="{{billing_profiles}}"
                        class="nav-link {% if request.path == billing_profiles %}active{% endif %}">
                        Mis métodos de pago <span class="fab fa-cc-stripe"></span>
                    </a>
                </li>
                {% endif %}
            </ul>
            <ul class="navbar-nav ms-auto">
                {% if user.is_authenticated %}
                <li class="navbar-item">
                    <a href="{% url 'logout' %}" class="nav-link">
                        <span class="fas fa-sign-in-alt "></span>
                        Logout
                    </a>
                </li>
                {% else %}
                <li class="navbar-item ">
                    <a href="{{login}}" class="nav-link {% if request.path == login %}active{% endif %}">
                        <span class="fas fa-user "></span>
                        Login
                    </a>
                </li>
                <li class="navbar-item ">
                    <a href="{{register}}" class="nav-link {% if request.path == register %}active{% endif %}">
                        <span class="fas fa-user-plus "></span>
                        Registro
                    </a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>